import org.apache.hadoop.fs.PathIOException;
public class FunctionUse3058 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.getTargetPath();
}
}